---
title: "About me"
---

Social sciences in the digital age face unique challenges that continue to fascinate me. Quantified facts are crucial for identifying action areas to prevent early-stage inequalities. Creating a just digitalized society and effectively managing digitalization's opportunities and risks will be a future challenge. Interdisciplinary approaches, connecting mathematical and IT methods with social science theories, are essential. I'm passionate about this challenge and eager to learn new methods while building a network of like-minded individuals.

## Work

-   **PHD Candidate in Social Sciences (Oct 2023 - Present)**

    I am currently a PhD student in the Youth Research Group at the [Centre for Childhood and Youth Research](https://www.jugend-in-luxemburg.lu) in the Department of Social Sciences. My research focuses on the relationship between media use and loneliness among young people.

-   **Research Assistant in Social Policy (May 2021 - September 2023)**

    In my role as a Research Assistant at the Chair of Social Policy, my research efforts were primarily focused on welfare state and perception of social inequality. I also contributed to various organizational tasks within the department.

## Presentations

+--------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 2024   | Analytical Sociology: Theory and Empirical Applications, *LMU and Venice International University, San Servolo, Italy*                                                                                                                                                   |
|        |                                                                                                                                                                                                                                                                          |
|        | „Digital Inequality and Social Media - Digital Divide: Profiling Luxembourg's Youth“ [Poster](https://hdl.handle.net/10993/64329) with [Gilles Scheifer](https://orbilu.uni.lu/profile?uid=50066876) & [Robin Samuel](https://www.researchgate.net/profile/Robin-Samuel) |
+--------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 2024   | PhD Conference in Social Science, *University of Luxembourg*                                                                                                                                                                                                             |
|        |                                                                                                                                                                                                                                                                          |
|        | „Digital Inequality and Social Media - Digital Divide: Profiling Luxembourg's Youth“ [Poster](https://hdl.handle.net/10993/64329) with [Gilles Scheifer](https://orbilu.uni.lu/profile?uid=50066876) & [Robin Samuel](https://www.researchgate.net/profile/Robin-Samuel) |
+--------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 2022   | Analytical Sociology: Theory and Empirical Applications, *LMU and Venice International University, San Servolo, Italy*                                                                                                                                                   |
|        |                                                                                                                                                                                                                                                                          |
|        | „Understanding Justice Attitudes- An Empirical Test of the Social Production Function (SPF)“ (Poster) with [Lea Schwan](https://www.researchgate.net/profile/Lea-Schwan)                                                                                                 |
+--------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 2021   | 3rd Conference Akademie für Soziologie – Cohesive Societies?, online, *University of Konstanz, Germany*                                                                                                                                                                  |
|        |                                                                                                                                                                                                                                                                          |
|        | „Deprivation and the Brexit Referendum: Analysing the Interplay between Regional and Individual Deprivation“ with [Tobias Rüttenauer](https://www.researchgate.net/profile/Tobias-Ruettenauer) & [Volker Ludwig](https://www.researchgate.net/profile/Volker-Ludwig)     |
+--------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+

## Teaching

+--------------------+--------------------------------------------------------------------------------------------------------------------------+
| 2023-2025          | Seminar (teaching assistant), B.A. Applied Social Research: Quantitative Methods, *University of Luxembourg, Luxembourg* |
+--------------------+--------------------------------------------------------------------------------------------------------------------------+
| 2022               | Seminar, B.A. Perception of Inequality and Justice, *University of Trier, Germany*                                       |
+--------------------+--------------------------------------------------------------------------------------------------------------------------+
|                    | Seminar, B.A. Gender Inequalities: Education and the Labour Market, *University of Trier, Germany*                       |
+--------------------+--------------------------------------------------------------------------------------------------------------------------+
|                    | Seminar, B.A. Poverty Policy, *University of Trier, Germany*                                                             |
+--------------------+--------------------------------------------------------------------------------------------------------------------------+
|                    | Seminar, B.A. Spatial Inequality, *University of Trier, Germany*                                                         |
+--------------------+--------------------------------------------------------------------------------------------------------------------------+
|                    | Seminar, M.A. Advanced Methods: Replications, *RPTU Kaiserslautern-Landau, Germany*                                      |
+--------------------+--------------------------------------------------------------------------------------------------------------------------+
| 2021               | Seminar B.A. Poverty Policy, *University of Trier, Germany*                                                              |
+--------------------+--------------------------------------------------------------------------------------------------------------------------+
|                    | Seminar B.A. Gender Inequalities: Education and the Labour Market, *University of Trier, Germany*                        |
+--------------------+--------------------------------------------------------------------------------------------------------------------------+
|                    | Seminar B.A. Introduction to Academic Research, *University of Trier, Germany*                                           |
+--------------------+--------------------------------------------------------------------------------------------------------------------------+
| 2016-2021          | Tutor, B.A. Methods of Empirical Social Research, *RPTU Kaiserslautern-Landau, Germany*                                  |
+--------------------+--------------------------------------------------------------------------------------------------------------------------+

~All courses were taught in German.~

## Education

-   **RPTU Kaiserslautern-Landau (2019 - 2021)**

    Master of Arts - Integrative Social Sciences

    -   Major in Sociology and Methods of Empirical Social Research
    -   Title of the Master’s thesis: „Deprivation and the Brexit referendum“. In cooperation with Nuffield College University of Oxford

-   **RPTU Kaiserslautern-Landau (2014 - 2019)**

    Bachelor of Arts - Integrative Social Sciences

    -   Major in Sociology
    -   Title of the Bachelor’s thesis: „Family and life satisfaction: the transition from LAT to cohabitation“

## Publications

### Peer-Reviewed Journal Article 

Haußmann, C., & Rüttenauer, T. (2024). Material deprivation and the Brexit referendum: a spatial multilevel analysis of the interplay between individual and regional deprivation. European Sociological Review, 40(3), 479-492. <https://doi.org/10.1093/esr/jcad057>

### Books & Others 
Bulut, H., Salza, G., Residori, C., Scheifer, G., Haußmann, C., & Samuel, R. (2025). Kapitel 5. Der Blick junger Menschen auf Digitalität: Zugänge, Nutzungsmuster und Teilhabe. In A. Schumacher, H. Käckmeister, & R. Samuel (Eds), Nationaler Bericht zur Situation der Jugend in Luxemburg 2025 (pp. 91–123). <https://orbilu.uni.lu/bitstream/10993/67940/1/JB25-KAPITEL05.pdf>

Residori, C., Bulut, H., Salza, G., Scheifer, G., Haußmann, C., & Samuel, R. (2025). Kapitel 4. Der Blick junger Menschen auf die Gesellschaft und sich selbst: Politik, Partizipation, soziales Umfeld, Freizeitverhalten und Wohlbefinden. In A. Schumacher, H. Käckmeister, & R. Samuel (Eds), Nationaler Bericht zur Situation der Jugend in Luxemburg 2025 (pp. 47–90). <https://orbilu.uni.lu/bitstream/10993/67936/1/JB25-KAPITEL04.pdf>

Residori, C., Bulut, H., Samuel, R., Şolcă, Ş. A., Haußmann, C., & Scheifer, G. (2025). Tabellenband mit Schlüsseldaten aus dem Youth Survey Luxembourg zum Jugendbericht 2025. <https://orbilu.uni.lu/bitstream/10993/67960/1/JB25-Tabellen.pdf>




